name: ci
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Bitcoin
        run: |
            sudo apt update
            sudo add-apt-repository ppa:luke-jr/bitcoincore
            sudo apt-get install bitcoind

      - name: Check bitcoind setup with version
        run: bitcoind --version
       
      - name: Config and start Bitcoin nodes
        run: |
            mkdir ~/.bitcoin/
            cat << EOF >> ~/.bitcoin/bitcoin.conf
            regtest=1
            daemon=1
            rpcuser=username
            rpcpassword=password
            rpcallowip=127.0.0.1
            EOF
            bitcoind -regtest -rpcport=18444
            sleep 5

      - name: Run
        run: cargo run
      
      - name: Test
        run: cargo test

      - name: Stop bitcoin node
        run: bitcoin-cli -regtest -rpcport=18444 stop
      
      # - name: Clippy
      #   run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Format
        run: cargo fmt --check